version: "3.9"
services:
  postgres:
    image: postgres:12.9
    environment:
      POSTGRES_DB: "netology-db"
      POSTGRES_USER: "vagrant"
      POSTGRES_PASSWORD: "xxxxxxx"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
      - ../Backup:/var/lib/postgresql/backup
    ports:
      - "5432:5432"