---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  remote_user: vagrant

  tasks:
    - name: Create directory for ssh-keys
      file: state=directory mode=0700 dest=/root/.ssh/

    - name: Adding rsa-key in /root/.ssh/authorized_keys
      copy: src=/vagrant_data/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      ignore_errors: yes
    - name: Checking DNS
      command: host -t A google.com
    - name: Installing tools
      apt: >
        package={{ item }}
        state=present
        update_cache=yes
      with_items:
        - git
        - curl

    - name: Installing docker part1
      shell: curl -fsSL get.docker.com -o /vagrant_data/ansible/get-docker.sh

    - name: Installing docker part2
      shell: chmod +x /vagrant_data/ansible/get-docker.sh

    - name: Installing docker part3
      shell: /vagrant_data/ansible/get-docker.sh

    - name: Add the current user to docker group
      user: name=vagrant append=yes groups=docker
